### ISSUE TITLE
Showing the country flag instead of the countr id for the language toggle

### ISSUE THREAD

**Issue by chrvt** [george-gca/multi-language-al-folio#11]
**Is your feature request related to a problem? Please describe.**
I find it not particularly aesthetic to have the country id for the language toggle.

**Describe the solution you'd like**
Instead of showing the idea, one can add the option to show the country flag.

**Describe alternatives you've considered**
I do not see any alternative. Of course, the country flags are optional, any .svg is possible.

**Additional context**
I already implemented the feature and it will look as follow:
<img width="777" alt="country-flag-language-toggle" src="https://github.com/george-gca/multi-language-al-folio/assets/55452142/6f55e4d1-fd19-4d2e-b22a-cf1b28441522">

**Comment by george-gca** [comment]
Implemented in the latest update.

**Comment by chrvt** [comment]
thank you @george-gca , I'm sorry for not being very responsive, I was a bit under water lately
