### ISSUE TITLE
Could not find gem 'jekyll-multiple-languages-plugin' in locally installed gems. (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by kfuku52** [george-gca/multi-language-al-folio#13]
**Describe the bug**
Thank you for providing this outstanding template for lab websites. I started using it yesterday and came across what appears to be a potential issue. While setting up the local environment using Docker, as per the instructions in [INSTALL.md](https://github.com/george-gca/multi-language-al-folio/blob/main/INSTALL.md), I encountered a snag. Specifically, after executing `docker compose up`, Docker seemed to hang, displaying the following messages. However, the server did successfully launch once I rebuilt the Docker image, after adding a new line `RUN gem install jekyll-multiple-languages-plugin` to Dockerfile.

Additionally, `INSTALL.md` mentions that the locally running template should be accessible at `http://localhost:8888`, but it actually is available at `http://localhost:8080`. This isn't a bug, but I thought it was worth mentioning for clarity.

```
kef74yk$ docker compose up
[+] Running 2/2
 ✔ Network kenji-fukushima-labgithubio_default     Created                                                                                        0.0s 
 ✔ Container kenji-fukushima-labgithubio-jekyll-1  Created                                                                                        0.9s 
Attaching to jekyll-1
jekyll-1  | /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/resolver.rb:332:in `raise_not_found!': Could not find gem 'jekyll-multiple-languages-plugin' in locally installed gems. (Bundler::GemNotFound)
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/resolver.rb:392:in `block in prepare_dependencies'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/resolver.rb:377:in `each'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/resolver.rb:377:in `map'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/resolver.rb:377:in `prepare_dependencies'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/resolver.rb:61:in `setup_solver'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/resolver.rb:28:in `start'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/definition.rb:600:in `start_resolution'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/definition.rb:311:in `resolve'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/definition.rb:553:in `materialize'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/definition.rb:203:in `specs'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/definition.rb:270:in `specs_for'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/runtime.rb:18:in `setup'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler.rb:162:in `setup'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/jekyll-4.3.3/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/jekyll-4.3.3/exe/jekyll:11:in `<top (required)>'
jekyll-1  | 	from /usr/local/bin/jekyll:25:in `load'
jekyll-1  | 	from /usr/local/bin/jekyll:25:in `<main>'
```

**System (please complete the following information):**

- OS: MacOS 13.6.3
- Browser (and its version): Chrome (but may not be relevant)
- Jekyll version: 4.3.3
- Ruby version:

**Comment by george-gca** [comment]
Thanks for pointing these out. I still haven't created the official docker image for this template, maybe it is time for me to prioritize this. As for the port, this was already identified and being handled in [this issue](https://github.com/alshedivat/al-folio/issues/2090).

**Comment by george-gca** [comment]
Just pushed the last few changes and the docker image was created. Can you update your code and test the new image @kfuku52?
