### ISSUE TITLE
Unnecessary Flag Dropdown Menu Width

### ISSUE THREAD

**Issue by DavidKrassnig** [george-gca/multi-language-al-folio#16]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/george-gca/multi-language-al-folio/blob/master/FAQ.md) and searched through the past issues both in the [original repo](https://github.com/alshedivat/al-folio/issues) and [this one](https://github.com/george-gca/multi-language-al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

When you have more than 2 languages active, the drowndown menu for language selection is comically wide when using flags (in relation to the size of the flags).

### How to reproduce the bug

1. Use three or more languages
2. Activate the use of flags in _config.yml
3. Build the website
4. Click on the flag to open the dropdown menu

### What operating system are you using?

Linux

### Where are you seeing the problem on?

Running locally without Docker, Deployed site

### More info

I don't use docker for this, but I assume the problem should persist there, too (just in case you are wondering why I haven't selected it).

Furthermore, here's a screenshot of the issue:
![Screenshot_2024-02-11_20-48-59_flag_dropdownlist](https://github.com/george-gca/multi-language-al-folio/assets/96623786/5535d554-e171-4edf-a35f-a8c84ce7f67f)

You can also see it live here:
https://david.krassnig.de/al-folio-crasnicius/

I assume the solution for this lies somewhere in the _sass folder, but I'm mostly illiterate when it comes to css/sass.

**Comment by george-gca** [comment]
Fixed in 436e60
