### ISSUE TITLE
Liquid Exception: Liquid syntax error (line 1): Unknown tag 'translate_file'

### ISSUE THREAD

**Issue by liuliu66** [george-gca/multi-language-al-folio#22]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/george-gca/multi-language-al-folio/blob/master/FAQ.md) and searched through the past issues both in the [original repo](https://github.com/alshedivat/al-folio/issues) and [this one](https://github.com/george-gca/multi-language-al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

build error Liquid Exception: Liquid syntax error (line 1): Unknown tag 'translate_file'

### How to reproduce the bug

When I commit and push it to github, the build error appears with 
Liquid Exception: Liquid syntax error (line 1): Unknown tag 'translate_file'
And the gh-pages branch is not generated?

how could I deal with this problem?

### Error messages and logs

```
The error message you got, with the full traceback if available. Please paste it between these triple backticks.
```

### What operating system are you using?

Windows

### Where are you seeing the problem on?

Deployed site

### More info

When I commit and push it to github, the build error appears with 
Liquid Exception: Liquid syntax error (line 1): Unknown tag 'translate_file'
And the gh-pages branch is not generated?

how could I deal with this problem?

**Comment by george-gca** [comment]
Your template must be updated to the latest version. As of [v1.11.1](https://github.com/george-gca/multi-language-al-folio/releases/tag/v1.11.0) `jekyll-multiple-languages-plugin` support was dropped in favor of `polyglot`. You can read more about it [here](https://github.com/george-gca/multi-language-al-folio?tab=readme-ov-file#multi-language-support).
