### ISSUE TITLE
Does not generate the docker image locally

### ISSUE THREAD

**Issue by tiagovercosa** [george-gca/multi-language-al-folio#38]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/george-gca/multi-language-al-folio/blob/main/FAQ.md) and searched through the past issues both in the [original repo](https://github.com/alshedivat/al-folio/issues) and [this one](https://github.com/george-gca/multi-language-al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

The image specified in the `docker-compose.yml` file was not found in the Docker Hub repository.

### How to reproduce the bug

Clone the project and use Docker to install Jekyll and the dependencies by running the following command in the terminal:

`docker compose pull`

It turns out that the image specified in the `docker-compose.yml` file was not found in the Docker Hub repository. The error message indicates that

`docker.io/georgegca/multi-language-al-folio:v1.13.0` does not exist.

So I edited the file `docker-compose.yml` and removed the tag and it worked correctly. But I don't know if I did the right thing by removing the tag.

### Error messages and logs

```
[+] Pulling 1/1
 ! jekyll Warning failed to resolve reference "docker.io/georgegca/multi-language-al-folio:v1.13.0": docker.i...                 1.9s
WARNING: Some service image(s) must be built from source by running:
    docker compose build jekyll
1 error occurred:
	* Error response from daemon: failed to resolve reference "docker.io/georgegca/multi-language-al-folio:v1.13.0": docker.io/georgegca/multi-language-al-folio:v1.13.0: not found
```

### What operating system are you using?

Mac

### Where are you seeing the problem on?

Running locally with Docker (docker compose)

**Comment by george-gca** [comment]
My mistake, it should have been version `1.13.1`. Fixed in https://github.com/george-gca/multi-language-al-folio/commit/736bb0d8421b2800cef1573e90b547fbbda2da1c.
